### ISSUE TITLE
Error appears when Multiple TF analysis results in no gene overlaps

### ISSUE THREAD

**Issue by aromanowski** [fran-romero-campero/ATTRACTOR#2]
**Describe the bug**
Error appears when Multiple TF analysis results in no gene overlaps: "An error has occurred. Check your logs or contact the app author for clarification."

**To Reproduce**
1. Go to 'Multiple transcription factor analysis'
2. Select:
PHYA ZT00
CCA1 ZT02
FHY ZT04
PIF4 ZT04
PIF5 ZT04
CCA1 ZT14
3. Click on 'Gene Table'

**Expected behavior**
A message saying that there is no overlap

**Screenshots**
![image](https://user-images.githubusercontent.com/1184114/81225277-deb3e800-8fe0-11ea-9d78-a42532a31d38.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by fran-romero-campero** [comment]
Thank you very much @aromanowski This was indeed a bug. We have now solved it as you suggested by including a message stating "The intersection between the target genes of the                                                    selected transcription factors is empty. The selected TFs do no have any common target genes. No further analysis can be performed."
